name: GoLang SAST

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sast:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.23

    - name: Install gosec
      run: GO111MODULE=on go get -v github.com/securego/gosec/v2/cmd/gosec@latest

    - name: Run SAST scan
      run: gosec -fmt=sarif ./...

    - name: Upload SARIF results
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: gosec.sarif
